name: dotnet-estimation building

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: build on ubuntu
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v3
   
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
    - name: build project
      run: dotnet build
      working-directory: ./dotnet-estimation
      
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./dotnet-estimation 
